application: series-downloader

version: 0-1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- remote_api: on
- deferred: on

handlers:
- url: /upload.*
  script: py.main.app
  secure: optional

- url: /getDownloadList.*
  script: py.main.app
  secure: optional

- url: /getURLResponse.*
  script: py.main.app
  secure: optional

- url: /checkDownloads.*
  script: py.main.app
  secure: optional

- url: /downloads.*
  script: py.main.app
  secure: optional

- url: /getInfo.*
  script: py.main.app
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  static_files: index.html
  upload: index.html

libraries:
- name: ssl
  version: latest
- name: jinja2
  version: "2.6"


skip_files:
# Default values from https://developers.google.com/appengine/docs/python/config/appconfig#Python_app_yaml_Skipping_files
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom values
- ^VENV.*$
- ^.*\.egg.*$
- ^gae/tmp/.*$
- ^dist/.*$
- ^docs/.*$
- ^test/.*$
- ^devscripts/.*$
- ^local/.$
- ^venv.*$
